# Generated by Django 3.0.7 on 2020-06-28 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insiderlist', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('post_office', '0008_attachment_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='email',
            name='anymail_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Anymail Message ID'),
        ),
        migrations.AddField(
            model_name='email',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer'),
        ),
        migrations.AddField(
            model_name='email',
            name='membership_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='email',
            name='membership_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(related_name='recipient_email', to='insiderlist.Contact'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='log',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer'),
        ),
        migrations.AddField(
            model_name='log',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='attachment_unique_to_issuer'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='email_unique_to_issuer'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='emailtemplate_unique_to_issuer'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'default_template'), name='unique_template_language'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='log_unique_to_issuer'),
        ),
    ]
