# Generated by Django 3.0.7 on 2020-06-28 22:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0009_auto_20200628_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='context_variables',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
