# Generated by Django 3.0.8 on 2020-07-10 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
import jsonfield.fields
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('insiderlist', '0001_initial'),
        ('post_office', '0009_requeued_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='email',
            name='anymail_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Anymail Message ID'),
        ),
        migrations.AddField(
            model_name='email',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
        migrations.AddField(
            model_name='email',
            name='membership_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='email',
            name='membership_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(related_name='recipient_email', to='insiderlist.Contact'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='context_variables',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='log',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
        migrations.AddField(
            model_name='log',
            name='obj_created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='obj_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='emails',
            field=models.ManyToManyField(related_name='attachments', to='post_office.Email', verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='email',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Email won't be sent after this timestamp", null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='email',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The scheduled sending time', null=True, verbose_name='Scheduled Time'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=froala_editor.fields.FroalaField(blank=True, validators=[post_office.validators.validate_template_syntax], verbose_name='HTML content'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='attachment_unique_to_issuer'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='email_unique_to_issuer'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='emailtemplate_unique_to_issuer'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'default_template'), name='unique_template_language'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('id', 'issuer_id'), name='log_unique_to_issuer'),
        ),
    ]
