# Generated by Django 3.0.8 on 2020-07-28 15:44

from django.db import migrations
import froala_editor.fields
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0010_auto_20200725_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, validators=[post_office.validators.validate_template_syntax], verbose_name='Content'),
        ),
    ]
