# Generated by Django 3.0.7 on 2020-06-29 18:19

from django.db import migrations
import froala_editor.fields
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0010_emailtemplate_context_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=froala_editor.fields.FroalaField(blank=True, validators=[post_office.validators.validate_template_syntax], verbose_name='HTML content'),
        ),
    ]
