# Generated by Django 3.0.8 on 2020-07-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insiderlist', '0001_initial'),
        ('post_office', '0010_auto_20200709_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
    ]
