# Generated by Django 3.0.8 on 2020-07-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insiderlist', '0001_initial'),
        ('post_office', '0010_auto_20200717_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer (optional)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer (optional)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer (optional)'),
        ),
        migrations.AlterField(
            model_name='log',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Issuer subject to MAR for delayed disclosure', null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer', verbose_name='Issuer (optional)'),
        ),
    ]
