# Generated by Django 3.0.7 on 2020-07-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0009_requeued_mode'),
        ('post_office', '0011_auto_20200629_1819'),
    ]

    operations = [
    ]
