# Generated by Django 3.0.8 on 2020-07-17 19:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_auto_20200717_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='context_variables',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
