# Generated by Django 3.0.8 on 2020-07-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insiderlist', '0001_initial'),
        ('post_office', '0011_auto_20200710_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
        migrations.AlterField(
            model_name='email',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
        migrations.AlterField(
            model_name='log',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insiderlist.Issuer'),
        ),
    ]
