# Generated by Django 3.0.8 on 2020-07-28 16:24

from django.db import migrations, models
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_auto_20200728_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, validators=[post_office.validators.validate_template_syntax], verbose_name='Content'),
        ),
    ]
