# Generated by Django 3.0.7 on 2020-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0012_merge_20200701_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Email won't be sent after this timestamp"),
        ),
    ]
