# Generated by Django 3.0.8 on 2020-07-17 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0013_auto_20200717_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='anymail_esp_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The raw response from the ESP API call. Varies by backend', null=True, verbose_name='Anymail ESP response'),
        ),
        migrations.AddField(
            model_name='email',
            name='anymail_message_id',
            field=models.CharField(blank=True, help_text='The message id assigned by the ESP, or None if the send call failed.', max_length=255, null=True, verbose_name='Anymail message ID'),
        ),
        migrations.AddField(
            model_name='email',
            name='anymail_recipients',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A dict of per-recipient status and message_id values.', null=True, verbose_name='Anymail recipients'),
        ),
        migrations.AddField(
            model_name='email',
            name='anymail_status',
            field=models.TextField(blank=True, help_text='A set of send statuses, across all recipients (to, cc, bcc) of the message, or None if the send call failed.', max_length=255, null=True, verbose_name='Anymail status'),
        ),
    ]
