# Generated by Django 3.0.8 on 2020-07-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0014_auto_20200717_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='email',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='post_office.Email', verbose_name='Email object'),
        ),
    ]
