# Generated by Django 3.0.8 on 2020-07-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0015_auto_20200718_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'failed')], null=True, verbose_name='Status'),
        ),
    ]
