# Generated by Django 3.0.8 on 2020-07-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0016_auto_20200718_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='exception_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exception type'),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
    ]
